# Generated by Django 4.0.2 on 2022-03-11 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_product_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-update', '-create']},
        ),
    ]
