# Generated by Django 4.0.2 on 2022-03-12 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='create',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='update',
            new_name='updated',
        ),
    ]
