# Generated by Django 4.0.2 on 2022-03-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_product_options_rename_create_product_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default_image.png', null=True, upload_to=''),
        ),
    ]
