# Generated by Django 4.0.2 on 2022-04-16 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.product')),
                ('company', models.TextField(blank=True, null=True)),
                ('publishDate', models.DateField()),
                ('width', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('numberPage', models.IntegerField(blank=True, null=True)),
                ('author', models.TextField(blank=True, null=True)),
                ('bookCategory', models.TextField()),
            ],
            bases=('base.product',),
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.product')),
                ('material', models.TextField(blank=True, null=True)),
                ('origin', models.TextField(blank=True, null=True)),
                ('brand', models.TextField(blank=True, null=True)),
                ('size', models.CharField(max_length=10)),
                ('type', models.TextField()),
            ],
            bases=('base.product',),
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.product')),
                ('brand', models.TextField(blank=True, null=True)),
                ('gen', models.TextField(blank=True, null=True)),
                ('pin', models.IntegerField(blank=True, null=True)),
                ('screenType', models.TextField(blank=True, null=True)),
                ('screenSize', models.FloatField(blank=True, null=True)),
                ('dpg', models.TextField(blank=True, null=True)),
                ('chip', models.FloatField(blank=True, null=True)),
                ('gpu', models.TextField(blank=True, null=True)),
                ('ram', models.IntegerField(blank=True, null=True)),
                ('rom', models.IntegerField(blank=True, null=True)),
                ('simNumber', models.IntegerField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('sizeOfPhone', models.TextField(blank=True, null=True)),
                ('bluetooth', models.CharField(choices=[('Yes', 'yes'), ('No', 'no')], default='Yes', max_length=10)),
            ],
            bases=('base.product',),
        ),
    ]
