# Generated by Django 4.0.2 on 2022-04-16 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_book_clothes_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
