# Generated by Django 4.0.2 on 2022-04-16 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_product_topic_delete_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='size',
            field=models.CharField(max_length=100),
        ),
    ]
