# Generated by Django 4.0.2 on 2022-04-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_rename_phone_mobilephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='type',
            field=models.TextField(blank=True, null=b'I01\n'),
        ),
    ]
