# Generated by Django 4.0.2 on 2022-04-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_mobilephone_brand_alter_mobilephone_chip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilephone',
            name='chip',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
