# Generated by Django 4.0.2 on 2022-04-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_mobilephone_chip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilephone',
            name='brand',
            field=models.TextField(blank=True, default='None', null=True),
        ),
        migrations.AlterField(
            model_name='mobilephone',
            name='chip',
            field=models.TextField(blank=True, default='None', null=True),
        ),
        migrations.AlterField(
            model_name='mobilephone',
            name='dpg',
            field=models.TextField(blank=True, default='None', null=True),
        ),
        migrations.AlterField(
            model_name='mobilephone',
            name='gen',
            field=models.TextField(blank=True, default='None', null=True),
        ),
        migrations.AlterField(
            model_name='mobilephone',
            name='gpu',
            field=models.TextField(blank=True, default='None', null=True),
        ),
        migrations.AlterField(
            model_name='mobilephone',
            name='screenType',
            field=models.TextField(blank=True, default='None', null=True),
        ),
        migrations.AlterField(
            model_name='mobilephone',
            name='sizeOfPhone',
            field=models.TextField(blank=True, default='None', null=True),
        ),
    ]
