# Generated by Django 4.0.2 on 2022-04-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_mobilephone_brand_alter_mobilephone_chip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.TextField(blank=True, default='None', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookCategory',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='book',
            name='company',
            field=models.TextField(blank=True, default='None', null=True),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='brand',
            field=models.TextField(blank=True, default='None', null=True),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='material',
            field=models.TextField(blank=True, default='None', null=True),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='origin',
            field=models.TextField(blank=True, default='None', null=True),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='type',
            field=models.TextField(blank=True, default='None', null=True),
        ),
    ]
