# Generated by Django 4.0.2 on 2022-04-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_book_author_alter_book_bookcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookCategory',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='company',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='brand',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='material',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='origin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mobilephone',
            name='brand',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mobilephone',
            name='chip',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mobilephone',
            name='dpg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mobilephone',
            name='gen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mobilephone',
            name='gpu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mobilephone',
            name='screenType',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mobilephone',
            name='sizeOfPhone',
            field=models.TextField(blank=True, null=True),
        ),
    ]
