# Generated by Django 4.0.2 on 2022-04-28 07:55

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_alter_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.TextField(blank=True, max_length=200, null=True)),
                ('province', models.TextField(blank=True, max_length=200, null=True)),
                ('district', models.TextField(blank=True, max_length=200, null=True)),
                ('ward', models.TextField(blank=True, max_length=200, null=True)),
                ('exact_address', models.TextField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.TextField(blank=True, default='customer', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fullName', models.TextField(blank=True, max_length=100, null=True)),
                ('SDT', models.CharField(blank=True, max_length=20, null=True)),
                ('adress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.address')),
            ],
            bases=('base.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
