# Generated by Django 4.0.2 on 2022-04-28 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_address_alter_orderproduct_options_user_position_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='bookCategory',
            new_name='book_Category',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='numberPage',
            new_name='number_Page',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='publishDate',
            new_name='publish_Date',
        ),
        migrations.RenameField(
            model_name='mobilephone',
            old_name='screenSize',
            new_name='screen_size',
        ),
        migrations.RenameField(
            model_name='mobilephone',
            old_name='screenType',
            new_name='screen_type',
        ),
        migrations.RenameField(
            model_name='mobilephone',
            old_name='simNumber',
            new_name='sim_number',
        ),
        migrations.RenameField(
            model_name='mobilephone',
            old_name='sizeOfPhone',
            new_name='size_of_phone',
        ),
    ]
