# Generated by Django 4.0.2 on 2022-04-28 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_rename_book_category_book_book_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='fullName',
            new_name='full_name',
        ),
    ]
