# Generated by Django 4.0.2 on 2022-04-28 09:01

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_rename_fullname_customer_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='position',
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('position', models.TextField(choices=[('Shipper', 'Shipper'), ('Product manager', 'Product Manager'), ('Employee manager', 'Employee Manager'), ('Order manager', 'Order manager')], max_length=100)),
                ('salary', models.IntegerField(default=0, help_text='VND')),
            ],
            bases=('base.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
