# Generated by Django 4.0.2 on 2022-04-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_remove_user_position_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='adress',
        ),
        migrations.AddField(
            model_name='customer',
            name='adress',
            field=models.ManyToManyField(blank=True, to='base.Address'),
        ),
    ]
