# Generated by Django 4.0.2 on 2022-04-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_employee_sdt_employee_adress_employee_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='SDT',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='SDT',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='full_name',
        ),
        migrations.AddField(
            model_name='user',
            name='SDT',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='adress',
            field=models.ManyToManyField(blank=True, to='base.Address'),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
