# Generated by Django 4.0.2 on 2022-04-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_remove_customer_sdt_remove_customer_adress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.TextField(blank=True, choices=[('Shipper', 'Shipper'), ('Product manager', 'Product Manager'), ('Employee manager', 'Employee Manager'), ('Order manager', 'Order manager')], max_length=100, null=True),
        ),
    ]
