# Generated by Django 4.0.2 on 2022-04-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_alter_employee_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='customer_or_employee',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Customer', 'Customer')], default='Customer', max_length=100),
        ),
    ]
