# Generated by Django 4.0.2 on 2022-04-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_user_customer_or_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='customer_or_employee',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Customer', 'Customer'), ('Admin', 'Admin')], default='Customer', max_length=100),
        ),
    ]
