# Generated by Django 4.0.2 on 2022-04-28 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
    ]
