# Generated by Django 4.0.2 on 2022-04-29 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_function_remove_user_customer_or_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='adress',
        ),
    ]
