# Generated by Django 4.0.2 on 2022-04-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_checkout'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='ward',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
