# Generated by Django 4.0.2 on 2022-05-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_rename_sdt_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='boolean',
            field=models.BooleanField(default=False),
        ),
    ]
