# Generated by Django 4.0.2 on 2022-05-02 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0048_address_boolean'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address'},
        ),
    ]
