# Generated by Django 4.0.2 on 2022-05-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0049_alter_address_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='status_order',
            field=models.TextField(choices=[('completed', 'completed'), ('delivering', 'delivering'), ('in warehouse', 'in warehouse')], default='in warehouse', max_length=50),
        ),
    ]
