# Generated by Django 4.0.2 on 2022-05-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0052_remove_checkout_cart_checkout_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_Items',
            field=models.ManyToManyField(blank=True, null=True, to='base.OrderProduct'),
        ),
    ]
