# Generated by Django 4.0.2 on 2022-05-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0053_alter_order_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_Items',
            field=models.ManyToManyField(blank=True, to='base.OrderProduct'),
        ),
    ]
