# Generated by Django 4.0.2 on 2022-05-03 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0055_remove_checkout_order_checkout_order_items_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='status_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_order', models.TextField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='checkout',
            name='status_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.status_order'),
        ),
    ]
