# Generated by Django 4.0.2 on 2022-05-03 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_status_order_alter_checkout_status_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='status_order',
            new_name='status_orderx',
        ),
    ]
