# Generated by Django 4.0.2 on 2022-05-03 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0057_rename_status_order_checkout_status_orderx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='status_orderx',
        ),
    ]
