# Generated by Django 4.0.2 on 2022-05-03 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0058_remove_checkout_status_orderx'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='status_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.status_order'),
        ),
    ]
