# Generated by Django 4.0.2 on 2022-05-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0059_checkout_status_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='status_order',
            field=models.TextField(choices=[('completed', 'completed'), ('delivering', 'delivering'), ('in warehouse', 'in warehouse')], default='in warehouse', max_length=50),
        ),
        migrations.DeleteModel(
            name='status_order',
        ),
    ]
