# Generated by Django 4.0.2 on 2022-05-19 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0063_checkout_payment_or_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
