# Generated by Django 4.0.2 on 2022-05-19 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0064_orderproduct_checked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='order_Items',
            new_name='order',
        ),
    ]
