# Generated by Django 4.0.2 on 2022-05-20 04:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0065_rename_order_items_checkout_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
